=== SitiBanc/LoveHome-AgentHelper/xml/object.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="objects" type="objects"></xs:element>
	<xs:complexType name="objects">
		<xs:sequence>
			<xs:element name="object" type="object" minOccurs="0" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="object">
		<xs:sequence>
			<xs:element name="name" type="xs:string"></xs:element>
			<xs:element name="address" type="address"></xs:element>
			<xs:element name="total_area" type="xs:float"></xs:element>
			<xs:element name="main_area" type="xs:float"></xs:element>
			<xs:element name="partition" type="partition"></xs:element>
			<xs:element name="floors" type="floors"></xs:element>
			<xs:element name="post_price" type="xs:float"></xs:element>
			<xs:element name="date_completed" type="xs:date"></xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:integer" use="required"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="address">
		<xs:sequence>
			<xs:element name="city" type="xs:string"></xs:element>
			<xs:element name="district" type="xs:string"></xs:element>
			<xs:element name="road" type="xs:string"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="partition">
		<xs:sequence>
			<xs:element name="room" type="xs:integer"></xs:element>
			<xs:element name="living_room" type="xs:integer"></xs:element>
			<xs:element name="restroom" type="xs:integer"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="floors">
		<xs:sequence>
			<xs:element name="total_floor" type="xs:integer"></xs:element>
			<xs:element name="floor" type="xs:string"></xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== SitiBanc/LoveHome-AgentHelper/xml/object.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="object.xsl"?>
<objects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="object.xsd">
	<object id="1">
		<name>逢甲大地坪洋房</name>
		<address>
			<city>台中市</city>
			<district>西屯區</district>
			<road>西安街</road>
		</address>
		<total_area>30.93</total_area>
		<main_area>30.93</main_area>
		<partition>
			<room>4</room>
			<living_room>2</living_room>
			<restroom>2</restroom>
		</partition>
		<floors>
			<total_floor>2</total_floor>
			<floor>1-2</floor>
		</floors>
		<post_price>880</post_price>
		<date_completed>1973-05-23</date_completed>
	</object>
	<object id="2">
		<name>興大投資透店</name>
		<address>
			<city>台中市</city>
			<district>南區</district>
			<road>興大路</road>
		</address>
		<total_area>43.83</total_area>
		<main_area>43.83</main_area>
		<partition>
			<room>6</room>
			<living_room>2</living_room>
			<restroom>2</restroom>
		</partition>
		<floors>
			<total_floor>3</total_floor>
			<floor>1</floor>
		</floors>
		<post_price>935</post_price>
		<date_completed>1980-10-03</date_completed>
	</object>
	<object id="3">
		<name>松江康泰精品美居</name>
		<address>
			<city>台北市</city>
			<district>中山區</district>
			<road>松江路</road>
		</address>
		<total_area>11.33</total_area>
		<main_area>8.08</main_area>
		<partition>
			<room>1</room>
			<living_room>1</living_room>
			<restroom>1</restroom>
		</partition>
		<floors>
			<total_floor>12</total_floor>
			<floor>12</floor>
		</floors>
		<post_price>928</post_price>
		<date_completed>1977-11-18</date_completed>
	</object>
	<object id="4">
		<name>美術館收租金店</name>
		<address>
			<city>台中市</city>
			<district>西區</district>
			<road>大忠南街</road>
		</address>
		<total_area>32.92</total_area>
		<main_area>17.74</main_area>
		<partition>
			<room>2</room>
			<living_room>2</living_room>
			<restroom>2</restroom>
		</partition>
		<floors>
			<total_floor>13</total_floor>
			<floor>1-2</floor>
		</floors>
		<post_price>888</post_price>
		<date_completed>1993-11-22</date_completed>
	</object>
	<object id="5">
		<name>櫻花家綻靚亮三房</name>
		<address>
			<city>台中市</city>
			<district>烏日區</district>
			<road>三榮路二段</road>
		</address>
		<total_area>46.7</total_area>
		<main_area>22.53</main_area>
		<partition>
			<room>3</room>
			<living_room>2</living_room>
			<restroom>2</restroom>
		</partition>
		<floors>
			<total_floor>12</total_floor>
			<floor>5</floor>
		</floors>
		<post_price>888</post_price>
		<date_completed>2014-12-27</date_completed>
	</object>
	<object id="6">
		<name>中醫德化優質小宅</name>
		<address>
			<city>台中市</city>
			<district>北區</district>
			<road>德化街</road>
		</address>
		<total_area>14.07</total_area>
		<main_area>12.53</main_area>
		<partition>
			<room>1</room>
			<living_room>1</living_room>
			<restroom>1</restroom>
		</partition>
		<floors>
			<total_floor>5</total_floor>
			<floor>5</floor>
		</floors>
		<post_price>228</post_price>
		<date_completed>1982-08-02</date_completed>
	</object>
	<object id="7">
		<name>中正區電梯兩房</name>
		<address>
			<city>台北市</city>
			<district>中正區</district>
			<road>中華路二段</road>
		</address>
		<total_area>13.09</total_area>
		<main_area>10.18</main_area>
		<partition>
			<room>2</room>
			<living_room>1</living_room>
			<restroom>1</restroom>
		</partition>
		<floors>
			<total_floor>7</total_floor>
			<floor>6</floor>
		</floors>
		<post_price>890</post_price>
		<date_completed>1980-10-18</date_completed>
	</object>
	<object id="8">
		<name>文化國小裝潢美寓</name>
		<address>
			<city>台北市</city>
			<district>北投區</district>
			<road>杏林二路</road>
		</address>
		<total_area>36.29</total_area>
		<main_area>31.96</main_area>
		<partition>
			<room>3</room>
			<living_room>2</living_room>
			<restroom>2</restroom>
		</partition>
		<floors>
			<total_floor>5</total_floor>
			<floor>5</floor>
		</floors>
		<post_price>1260</post_price>
		<date_completed>1981-06-15</date_completed>
	</object>
	<object id="9">
		<name>天母國小美廈</name>
		<address>
			<city>台北市</city>
			<district>士林區</district>
			<road>天母西路</road>
		</address>
		<total_area>20.54</total_area>
		<main_area>10.49</main_area>
		<partition>
			<room>1</room>
			<living_room>1</living_room>
			<restroom>1</restroom>
		</partition>
		<floors>
			<total_floor>6</total_floor>
			<floor>4</floor>
		</floors>
		<post_price>1436</post_price>
		<date_completed>1992-05-30</date_completed>
	</object>
	<object id="10">
		<name>附中菁選集３樓</name>
		<address>
			<city>台北市</city>
			<district>大安區</district>
			<road>信義路三段</road>
		</address>
		<total_area>11.78</total_area>
		<main_area>6.35</main_area>
		<partition>
			<room>0</room>
			<living_room>1</living_room>
			<restroom>1</restroom>
		</partition>
		<floors>
			<total_floor>14</total_floor>
			<floor>3</floor>
		</floors>
		<post_price>1798</post_price>
		<date_completed>2007-02-02</date_completed>
	</object>
</objects>
